"""Initial migration with gender support

Revision ID: 1f3c37b98c4d
Revises: 
Create Date: 2025-09-24 12:19:01.785506

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision = '1f3c37b98c4d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop tokens table and index if they exist (safe migration)
    connection = op.get_bind()
    
    # Check if index exists before dropping
    result = connection.execute(text("""
        SELECT 1 FROM pg_indexes 
        WHERE indexname = 'ix_tokens_id'
    """)).fetchone()
    
    if result:
        op.drop_index(op.f('ix_tokens_id'), table_name='tokens')
    
    # Check if table exists before dropping
    result = connection.execute(text("""
        SELECT 1 FROM information_schema.tables 
        WHERE table_name = 'tokens'
    """)).fetchone()
    
    if result:
        op.drop_table('tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('tokens_pkey'))
    )
    op.create_index(op.f('ix_tokens_id'), 'tokens', ['id'], unique=False)
    # ### end Alembic commands ###